# 基于镜像ubuntu
FROM dorowu/ubuntu-desktop-lxde-vnc as builder
# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"
# 安装环境
RUN set -x \
    # 安装基本
    && apt-get update \
    && apt-get install -y gnupg libgconf-2-4 \
    # 安装NODE
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    # 安装TYPESCRIPT
    && npm install -g typescript@3.9.9 \
    # 安装uglifyjs
    && npm install -g uglify-es \
    # 安装tslint
    && npm install -g tslint \
    # 安装JDK
    && apt-get install -y openjdk-8-jdk \
    # 安装MAVEN
    && apt-get install -y maven \
    # 安装git
    && apt-get install -y git \
    # 安装转码工具
    && apt-get install -y dos2unix \
    # 安装解压工具
    && apt-get install -y unzip \
    && apt-get install -y unrar \
    # 删除源
    && apt-get autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*
# 环境变量-JAVA目录
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
# 环境变量-MAVEN目录
ENV MAVEN_HOME /usr/share/maven

# 安装tfs代码获取工具
ARG GIT_TF_VERSION=2.0.3.20131219
RUN set -x \
    # 下载GIT-TF
    && curl -sL https://download.microsoft.com/download/A/E/2/AE23B059-5727-445B-91CC-15B7A078A7F4/git-tf-${GIT_TF_VERSION}.zip -O \
    # 解压安装
    && unzip -o git-tf-${GIT_TF_VERSION}.zip -d /usr/share/ \
    && ln -s /usr/share/git-tf-${GIT_TF_VERSION}/git-tf /usr/bin/git-tf \
    # 删除文件
    && rm -rf ./git-tf-${GIT_TF_VERSION}.zip
# 设置环境变量
ENV GITTF_HOME /usr/share/git-tf-${GIT_TF_VERSION}/

# 安装tfs代码获取工具
ARG TEE_VERSION=14.123.1
RUN set -x \
    # 下载TEE
    && curl -L https://github.com/Microsoft/team-explorer-everywhere/releases/download/${TEE_VERSION}/TEE-CLC-${TEE_VERSION}.zip -O \
    # 解压安装
    && unzip -o TEE-CLC-${TEE_VERSION}.zip -d /usr/share/ \
    && ln -s /usr/share/TEE-CLC-${TEE_VERSION}/tf /usr/bin/tf \
    # 删除文件
    && rm -rf ./TEE-CLC-${TEE_VERSION}.zip
# 设置环境变量
ENV TF_CLC_HOME /usr/share/TEE-CLC-${TEE_VERSION}/

# 环境变量-代码目录
ENV CODE_HOME=/root/codes
# 初始化环境
RUN mkdir -p ${CODE_HOME}


# 编译基本项目
FROM builder as compiler
# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"
# 获取代码并编译
RUN set -x \
    && cd ${CODE_HOME} \
    && git clone --depth 1 https://github.com/color-coding/ibas-framework.git \
    && cd ibas-framework \
    && ./compile_packages.sh
# 获取代码并编译
RUN set -x \
    && cd ${CODE_HOME} \
    && git clone --depth 1 https://github.com/color-coding/btulz.transforms.git \
    && cd btulz.transforms \
    && ./compile_packages.sh
# 清理ibas相关缓存
RUN set -x \
    && rm -rf /root/.m2/repository/org/colorcoding

# 发布镜像
FROM builder
# 缓存maven仓库
COPY --from=compiler /root/.m2 /root/.m2/