# 基于镜像ubuntu
FROM dorowu/ubuntu-desktop-lxde-vnc

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 安装环境
RUN set -x \
    # 安装基本
    && apt-get update \
    && apt-get install -y gnupg libgconf-2-4 \
    # 安装NODE
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs \
    # 安装TYPESCRIPT
    && npm install -g typescript \
    # 安装uglifyjs
    && npm install -g uglify-es \
    # 安装tslint
    && npm install -g tslint \
    # 安装JDK
    && apt-get install -y openjdk-8-jdk \
    # 安装MAVEN
    && apt-get install -y maven \
    # 安装git
    && apt-get install -y git \
    # 安装转码工具
    && apt-get install -y dos2unix \
    # 删除源
    && apt-get autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

# 环境变量-JAVA目录
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
# 环境变量-MAVEN目录
ENV MAVEN_HOME /usr/share/maven

# 环境变量-代码目录
ENV CODE_HOME=/root/code
# 初始化环境
RUN mkdir -p ${CODE_HOME}
