# 基于镜像ubuntu
FROM dorowu/ubuntu-desktop-lxde-vnc as builder
# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"
# 安装环境
RUN set -x \
    # 安装基本
    && apt-get update \
    # 安装git
    && apt-get install -y git \
    # 安装转码工具
    && apt-get install -y dos2unix \
    # 安装解压工具
    && apt-get install -y unzip \
    && apt-get install -y unrar \
    # 安装docker
    && apt-get install -y docker.io \
    # 删除源
    && apt-get autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*
