# 基于官方tomcat镜像
FROM tomcat:8.5-alpine

# 作者
MAINTAINER Niuren.Zhu "niuren.zhu@icloud.com"

# 安装工具
RUN set -x \
# 更新源
    && apk update \
# 安装UNZIP
    && apk add --no-cache unzip curl \
# 删除源
    && rm -rf /var/cache/apk/*

# 创建数据文件夹
RUN set -x \
    && mkdir -p ${CATALINA_HOME}/ibas/ \
    && mkdir -p ${CATALINA_HOME}/ibas_tools/ \
    && rm -rf ${CATALINA_HOME}/webapps \
    && mkdir -p ${CATALINA_HOME}/webapps

# 拷贝配置文件
COPY conf/* ${CATALINA_HOME}/conf/
COPY ibas/* ${CATALINA_HOME}/ibas/
COPY ibas_tools/* ${CATALINA_HOME}/ibas_tools/
COPY deploy_apps.sh ${CATALINA_HOME}/deploy_apps.sh
COPY initialize_datas_ash.sh ${CATALINA_HOME}/initialize_datas.sh
COPY initialize_datastructures_ash.sh ${CATALINA_HOME}/initialize_datastructures.sh

VOLUME ${CATALINA_HOME}/ibas/
