# 基于官方tomcat镜像
FROM tomcat:8.5

# 作者
MAINTAINER Niuren.Zhu "niuren.zhu@icloud.com"

# 安装工具
RUN set -x \
# 更新源
    && apt-get update \
# 安装UNZIP
    && apt-get install -y unzip \
# 删除源
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 创建数据文件夹
RUN set -x \
    && mkdir -p ${CATALINA_HOME}/ibas \
    && mkdir -p ${CATALINA_HOME}/ibas/conf \
    && mkdir -p ${CATALINA_HOME}/ibas/data \
    && mkdir -p ${CATALINA_HOME}/ibas/logs \
    && mkdir -p ${CATALINA_HOME}/ibas_tools \
    && rm -rf ${CATALINA_HOME}/webapps \
    && mkdir -p ${CATALINA_HOME}/webapps

# 拷贝配置文件
COPY conf/* ${CATALINA_HOME}/conf/
COPY ibas/ ${CATALINA_HOME}/ibas/
COPY ibas_tools/ ${CATALINA_HOME}/ibas_tools/
COPY deploy_apps.sh ${CATALINA_HOME}/deploy_apps.sh
COPY initialize_datas.sh ${CATALINA_HOME}/initialize_datas.sh
COPY initialize_datastructures.sh ${CATALINA_HOME}/initialize_datastructures.sh

RUN chmod 775 ${CATALINA_HOME}/*.sh

VOLUME ${CATALINA_HOME}/ibas/
