# 基于[windows server core]镜像
FROM colorcoding/tomcat:8.5-wincore

# 使用Powershell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 安装工具
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z1900-x64.msi" -OutFile 'C:\7zip.msi'; \
    $proc = Start-Process -FilePath "msiexec.exe" -ArgumentList '/i', 'C:\7zip.msi', '/quiet' -Wait -Passthru; $proc.WaitForExit(); \
    IF ($proc.ExitCode -ne 0) { \
        Write-Host 'FAILED installing 7-ZIP!'; exit 1; \
    }; \
    Remove-Item -Force -LiteralPath 'C:\7zip.msi'; \    
    SETX /m PATH $(${Env:PATH} + \";${Env:ProgramFiles}\\7-zip\");

# 安装BTULZ
RUN Invoke-WebRequest -Uri "http://maven.colorcoding.org/repository/maven-releases/org/colorcoding/tools/btulz.scripts/latest/btulz.scripts-latest.tar" -OutFile 'C:\btulz.scripts.tar'; \
    $proc = Start-Process -FilePath "7z.exe" -ArgumentList 'x', 'C:\btulz.scripts.tar', '-oC:\temp\' -Wait -Passthru; $proc.WaitForExit(); \
    IF ($proc.ExitCode -ne 0) { \
        Write-Host 'FAILED untar SCRIPTS!'; exit 1; \
    }; \
    Copy-Item 'C:\temp\ibas\deploy_apps.bat' \"${Env:CATALINA_HOME}\"; \
    Copy-Item 'C:\temp\ibas\initialize_apps.bat' \"${Env:CATALINA_HOME}\"; \
    Remove-Item -Force -LiteralPath 'C:\btulz.scripts.tar'; \
    Invoke-WebRequest -Uri "http://maven.colorcoding.org/repository/maven-releases/org/colorcoding/tools/btulz.transforms/latest/btulz.transforms-latest.tar" -OutFile 'C:\btulz.transforms.tar'; \
    $proc = Start-Process -FilePath "7z.exe" -ArgumentList 'x', 'C:\btulz.transforms.tar', '-oC:\temp\ibas_tools' -Wait -Passthru; $proc.WaitForExit(); \
    IF ($proc.ExitCode -ne 0) { \
        Write-Host 'FAILED untar TRANSFORMS!'; exit 1; \
    }; \
    Copy-Item 'C:\temp\ibas_tools' "${Env:CATALINA_HOME}" -Recurse; \
    Remove-Item -Force -LiteralPath 'C:\btulz.transforms.tar'; \
    Remove-Item -Force -LiteralPath 'C:\temp\' -Recurse;

# 拷贝配置文件
COPY conf/* ${CATALINA_HOME}/conf/
# COPY ibas/ ${CATALINA_HOME}/ibas/ 挂载非空目录报错
