# 基于官方tomcat镜像
FROM tomcat:8.5

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 安装工具
RUN set -x \
    # 更新源
    && apt-get update \
    # 安装解压、时区设置
    && apt-get install -y unzip tzdata \
    # 安装字体
    && apt-get install -y fontconfig ttf-dejavu \
    # 删除源
    && apt-get autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

# 创建数据文件夹
RUN set -x \
    && mkdir -p ${CATALINA_HOME}/ibas/conf \
    && mkdir -p ${CATALINA_HOME}/ibas/data \
    && mkdir -p ${CATALINA_HOME}/ibas/logs \
    && mkdir -p ${CATALINA_HOME}/ibas_tools \
    && mkdir -p ${CATALINA_HOME}/ibas_lib

# 下载并部署工具
RUN set -x \
    && curl -fsSL -o /tmp/btulz.transforms.tar http://maven.colorcoding.org/repository/maven-releases/org/colorcoding/tools/btulz.transforms/latest/btulz.transforms-latest.tar \
    && tar -xvf /tmp/btulz.transforms.tar -C ${CATALINA_HOME}/ibas_tools \
    && rm -f /tmp/btulz.transforms.tar \
    && curl -fsSL -o /tmp/btulz.scripts.tar http://maven.colorcoding.org/repository/maven-releases/org/colorcoding/tools/btulz.scripts/latest/btulz.scripts-latest.tar \
    && mkdir -p /tmp/btulz.scripts \
    && tar -xvf /tmp/btulz.scripts.tar -C /tmp/btulz.scripts \
    && rm -f /tmp/btulz.scripts.tar \
    && cp -f /tmp/btulz.scripts/ibas/deploy_apps.sh ${CATALINA_HOME}/deploy_apps.sh \
    && cp -f /tmp/btulz.scripts/ibas/initialize_apps.sh ${CATALINA_HOME}/initialize_apps.sh \
    && rm -rf /tmp/btulz.scripts

# 拷贝配置文件
COPY conf/* ${CATALINA_HOME}/conf/
COPY ibas/ ${CATALINA_HOME}/ibas/

