# 基于[windows nano server]镜像
FROM colorcoding/tomcat:ibas-wincore as installer

# 拷贝tomcat文件
FROM colorcoding/tomcat:8.5-winnano

COPY conf/* ${CATALINA_HOME}/conf/
COPY ibas/ ${CATALINA_HOME}/ibas/

ENV PATH="${PATH};${ProgramFiles}/7-zip/"

COPY --from=installer ["${ProgramFiles}/7-zip/7z.exe", "${ProgramFiles}/7-zip/7z.exe"]
COPY --from=installer ["${ProgramFiles}/7-zip/7z.dll", "${ProgramFiles}/7-zip/7z.dll"]
COPY --from=installer ["${CATALINA_HOME}/deploy_apps.bat", "${CATALINA_HOME}/deploy_apps.bat"]
COPY --from=installer ["${CATALINA_HOME}/initialize_apps.bat", "${CATALINA_HOME}/initialize_apps.bat"]
COPY --from=installer ["${CATALINA_HOME}/ibas_tools", "${CATALINA_HOME}/ibas_tools"]
