# escape=`
# 基于官方[windows server core]镜像
FROM microsoft/windowsservercore

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 使用Powershell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 安装JAVA, jre-8u191-windows-x64
ENV JAVA_BUNDLEID 235727_2787e4a523244c269598db4e85c51e0c
ENV JAVA_VERSION jre1.8.0_191
RUN Invoke-WebRequest -Uri "http://javadl.oracle.com/webapps/download/AutoDL?BundleId=${Env:JAVA_BUNDLEID}" -OutFile 'C:\java-windows-x64.exe'; `
    Start-Process -FilePath 'C:\java-windows-x64.exe' -ArgumentList "/s" -Wait -NoNewWindow; `
    Remove-Item -Force -LiteralPath 'C:\java-windows-x64.exe'; `
    Remove-Item -Force -Recurse ${Env:TEMP}\*;
RUN setx /m JRE_HOME \"${Env:ProgramFiles}\JAVA\${Env:JAVA_VERSION}\"
RUN setx /m PATH $(${Env:PATH} + \";${Env:JRE_HOME}\bin\")

# 安装TOMCAT, v8.5.35
ENV TOMCAT_VERSION 8.5.35
ENV TOMCAT_HOME "C:\apache-tomcat-${TOMCAT_VERSION}"
RUN Invoke-WebRequest -Uri "http://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-8/v${Env:TOMCAT_VERSION}/bin/apache-tomcat-${Env:TOMCAT_VERSION}-windows-x64.zip" -OutFile 'C:\apache-tomcat.zip'; `
    Expand-Archive -LiteralPath 'C:\apache-tomcat.zip' -DestinationPath 'C:\'; `
    Remove-Item -Force -LiteralPath 'C:\apache-tomcat.zip'; `
    Remove-Item -Force -Recurse ${Env:TEMP}\*;
RUN setx /m CATALINA_HOME ${Env:TOMCAT_HOME}
RUN setx /m PATH $(${Env:PATH} + \";${Env:CATALINA_HOME}\bin\")

# 拷贝配置文件
COPY conf/* ${TOMCAT_HOME}/conf/

# 运行TOMCAT
EXPOSE 8080
SHELL ["cmd", "/S", "/C"]
CMD ["catalina.bat", "run"]
