# 第一步，编译应用
FROM colorcoding/compiling:ibas-alpine as compiler

# 拷贝应用清单
COPY applist.txt ${CODE_HOME}/compile_order.txt

# 设置环境（脚本，清单等）
ARG GIT_URL=https://github.com
RUN set -x \
    && cd ${CODE_HOME} \
    && git clone --depth 1 ${GIT_URL}/color-coding/btulz.scripts.git \
    && chmod +x ${CODE_HOME}/btulz.scripts/ibas/*.sh \
    && ln -s ${CODE_HOME}/btulz.scripts/ibas/builds.sh ${CODE_HOME}/builds.sh \
    && ln -s ${CODE_HOME}/btulz.scripts/ibas/compiles.sh ${CODE_HOME}/compiles.sh \
    && ln -s ${CODE_HOME}/btulz.scripts/ibas/copy_wars.sh ${CODE_HOME}/copy_wars.sh \
    && ln -s ${CODE_HOME}/btulz.scripts/ibas/gits.sh ${CODE_HOME}/gits.sh

# 下载代码并编译
RUN set -x \
    && cd ${CODE_HOME} \
    && ./gits.sh clone --depth 1 ${GIT_URL}/color-coding/ \
    && ./builds.sh \
    && ./compiles.sh \
    && ./copy_wars.sh ${CODE_HOME}

# 第二步，部署应用
FROM colorcoding/tomcat:ibas-alpine as deployer
# 拷贝应用包
COPY --from=compiler /root/codes/ibas_packages /usr/local/tomcat/ibas_packages/
# 释放应用包
RUN set -x \
    && cd ${CATALINA_HOME} \
    && ./deploy_apps.sh

# 第三步，构建运行容器
FROM colorcoding/tomcat:ibas-alpine as runner
COPY --from=deployer /usr/local/tomcat/ibas /usr/local/tomcat/ibas/
COPY --from=deployer /usr/local/tomcat/ibas_lib /usr/local/tomcat/ibas_lib/
COPY --from=deployer /usr/local/tomcat/webapps /usr/local/tomcat/webapps/

