ARG BASE_TAG="1.15.0"
ARG BASE_IMAGE="core-alpine-317"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV DISTRO=alpine317
ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV SKIP_CLEAN=true \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/alpine/install/tools/install_tools_deluxe.sh \
    /alpine/install/chromium/install_chromium.sh \
    # /alpine/install/firefox/install_firefox.sh \
    /alpine/install/remmina/install_remmina.sh \
    /alpine/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
    for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
    done && \
    $STARTUPDIR/set_user_permission.sh $HOME && \
    rm -f /etc/X11/xinit/Xclients && \
    chown 1000:0 $HOME && \
    mkdir -p /home/kasm-user && \
    chown -R 1000:0 /home/kasm-user && \
    rm -Rf ${INST_DIR}

# Set system permissions
RUN set -x \
    && filePath=$(which Xvnc) \
    && if [ -e $filePath ]; then setcap "cap_net_bind_service=+eip" $filePath; fi

# Userspace Runtime 
ENV HOME=/home/kasm-user
ENV VNC_PW 1q2w3e
ENV NO_VNC_PORT 80
WORKDIR $HOME

USER 1000

CMD ["--tail-log"]