# 基于镜像ubuntu
FROM accetto/ubuntu-vnc-xfce-firefox-g3:20.04

USER root
# 安装常用软件
RUN set -x \
    && DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    curl aria2 iputils-ping p7zip-full \
    ttf-wqy-zenhei xarchiver thunar-archive-plugin \
    # 删除源
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*
# 设置系统权限
RUN set -x \
    && filePath=$(which python3) \
    && if [ -L $filePath ]; then filePath=$(readlink -f $filePath); fi \
    && if [ -e $filePath ]; then setcap "cap_net_bind_service=+eip" $filePath; fi

# 调整参数
ENV NOVNC_PORT=80 \
    TINI_SUBREAPER=1

EXPOSE ${NOVNC_PORT}

USER "${HEADLESS_USER_ID}"
