# 基于镜像ubuntu
FROM linuxserver/webtop:ubuntu-xfce

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

RUN set -x \
    && DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    curl aria2 iputils-ping \
    ttf-wqy-zenhei xarchiver thunar-archive-plugin \
    # 删除源
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

# 设置环境变量
ENV CUSTOM_PORT 80
ENV CUSTOM_HTTPS_PORT 443
ENV START_DOCKER false

# 暴露端口
EXPOSE ${CUSTOM_PORT} ${CUSTOM_HTTPS_PORT}