# 基于[windows server core 2016]镜像
FROM mcr.microsoft.com/windows/servercore:ltsc2016

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 安装证书（系统根证书已到期）
# https://letsencrypt.org/certs/isrgrootx1.der
# https://letsencrypt.org/certs/isrg-root-x2.der
# https://letsencrypt.org/certs/lets-encrypt-r3.der
COPY certs C:\\Certs
RUN Get-ChildItem 'C:\Certs' | ForEach-Object -Process { \
    IF($_ -is [System.IO.FileInfo]) { \
    Import-Certificate -FilePath $_.FullName -CertStoreLocation 'Cert:\LocalMachine\Root' ; \
    } \
    }; \
    Remove-Item -Force -Recurse -LiteralPath 'C:\Certs\';

# 安装Nginx
ARG NGINX_VERSION=1.28.0
ENV NGINX_HOME C:\\nginx
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -Uri https://nginx.org/download/nginx-${Env:NGINX_VERSION}.zip -O nginx.zip; \
    Expand-Archive -LiteralPath nginx.zip -DestinationPath 'C:\'; \
    Move-Item -Path ${Env:NGINX_HOME}-${Env:NGINX_VERSION} ${Env:NGINX_HOME}; \
    Remove-Item nginx.zip -Force;

COPY conf/win.nginx.conf C:/nginx/conf/nginx.conf

SHELL ["cmd", "/S", "/C"]

WORKDIR ${NGINX_HOME}
ENTRYPOINT ["nginx.exe"]
EXPOSE 80 443