# 基于镜像ubuntu
FROM colorcoding/webtop:ubuntu

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

USER root

RUN set -x \
    && DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    unzip dos2unix git nodejs npm \
    # vscode依赖,tfs依赖
    libsecret-1-0 libnss3 gnupg libxss1 libxtst6 libkrb5-dev \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

# jdk8
ENV JAVA_VERSION=jdk8u412-b08_openj9-0.44.0
ARG JAVA_ESUM=85af2c57078aab240ce31ba3f7a8e86696ff5bdf4c30f3c37f107986f07b23a6
ARG JAVA_BINARY_URL='https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u412-b08_openj9-0.44.0/ibm-semeru-open-jdk_x64_linux_8u412b08_openj9-0.44.0.tar.gz'
RUN set -x \
    && curl -LfsSo /tmp/openjdk.tar.gz ${JAVA_BINARY_URL} \
    && echo "${JAVA_ESUM} */tmp/openjdk.tar.gz" | sha256sum -c - \
    && mkdir -p /opt/java/openjdk && mkdir -p /opt/java/.scc \
    && cd /opt/java/openjdk \
    && tar -xf /tmp/openjdk.tar.gz --strip-components=1 \
    && rm -rf /tmp/openjdk.tar.gz
ENV JAVA_HOME=/opt/java/openjdk \
    PATH="/opt/java/openjdk/bin:$PATH"

# maven
ARG MAVEN_SHA=332088670d14fa9ff346e6858ca0acca304666596fec86eea89253bd496d3c90deae2be5091be199f48e09d46cec817c6419d5161fb4ee37871503f472765d00
ARG MAVEN_BINARY_URL=https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
RUN set -x \
    && mkdir -p /usr/share/maven \
    && curl -fsSL -o /tmp/apache-maven.tar.gz ${MAVEN_BINARY_URL} \
    && echo "${MAVEN_SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
    && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
    && rm -f /tmp/apache-maven.tar.gz \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
ENV MAVEN_HOME /usr/share/maven
COPY conf/maven.settings.xml ${MAVEN_HOME}/conf/settings.xml

# typescript
RUN set -x \
    && npm install -g typescript@3.9.10 uglify-es 

# vscode
RUN curl -LfsSo /tmp/vscode_amd64.deb 'https://update.code.visualstudio.com/1.48.2/linux-deb-x64/stable' \
    && dpkg -i /tmp/vscode_amd64.deb \
    && rm -rf /tmp/vscode_amd64.deb \
    && echo '[Desktop Entry]'                               >/usr/share/applications/code.desktop \
    && echo 'Name=Visual Studio Code'                       >>/usr/share/applications/code.desktop \
    && echo 'Comment=Code Editing. Redefined.'              >>/usr/share/applications/code.desktop \
    && echo 'Exec=/usr/share/code/code --user-data-dir --no-sandbox --unity-launch %F'    >>/usr/share/applications/code.desktop \
    && echo 'Icon=com.visualstudio.code'                    >>/usr/share/applications/code.desktop \
    && echo 'Type=Application'                              >>/usr/share/applications/code.desktop \
    && echo 'Terminal=false'                                >>/usr/share/applications/code.desktop \
    && echo 'StartupNotify=false'                           >>/usr/share/applications/code.desktop \
    && echo 'StartupWMClass=Code'                           >>/usr/share/applications/code.desktop \
    && echo 'Categories=Development;IDE;'                   >>/usr/share/applications/code.desktop

# eclipse jee
RUN curl -LfsSo /tmp/eclipse.tar.gz 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2020-06/R/eclipse-jee-2020-06-R-linux-gtk-x86_64.tar.gz' \
    && mkdir -p /usr/share/eclipse \
    && cd /usr/share/eclipse \
    && tar -xf /tmp/eclipse.tar.gz --strip-components=1 \
    && rm -rf /tmp/eclipse.tar.gz \
    && echo '[Desktop Entry]'                    >/usr/share/applications/eclipse.desktop \
    && echo 'Name=Eclipse'                       >>/usr/share/applications/eclipse.desktop \
    && echo 'Comment=Eclipse'                    >>/usr/share/applications/eclipse.desktop \
    && echo 'Exec=/usr/share/eclipse/eclipse'    >>/usr/share/applications/eclipse.desktop \
    && echo 'Icon=/usr/share/eclipse/icon.xpm'   >>/usr/share/applications/eclipse.desktop \
    && echo 'Terminal=false'                     >>/usr/share/applications/eclipse.desktop \
    && echo 'Type=Application'                   >>/usr/share/applications/eclipse.desktop \
    && echo 'Categories=Development;IDE;'        >>/usr/share/applications/eclipse.desktop \
    && echo 'StartupNotify=false'                >>/usr/share/applications/eclipse.desktop

# tfs plugin
ARG TEE_VERSION=14.139.0
RUN \
    # plugin
    curl -LfsSo /tmp/TFSEclipsePlugin.zip https://github.com/microsoft/team-explorer-everywhere/releases/download/${TEE_VERSION}/TFSEclipsePlugin-UpdateSiteArchive-${TEE_VERSION}.zip \
    && unzip -o /tmp/TFSEclipsePlugin.zip -d /tmp/TFSEclipsePlugin \
    && mv /tmp/TFSEclipsePlugin/features/*.jar /usr/share/eclipse/features/ \
    && mv /tmp/TFSEclipsePlugin/plugins/*.jar /usr/share/eclipse/plugins/ \
    && rm -rf /tmp/TFSEclipsePlugin.zip /tmp/TFSEclipsePlugin \
    # tools
    && curl -LfsSo /tmp/TEE-CLC.zip https://github.com/microsoft/team-explorer-everywhere/releases/download/${TEE_VERSION}/TEE-CLC-${TEE_VERSION}.zip \
    && unzip -o /tmp/TEE-CLC.zip -d /usr/share/ \
    && ln -s /usr/share/TEE-CLC-${TEE_VERSION}/tf /usr/bin/tf \
    && rm -rf /tmp/TEE-CLC.zip
ENV TF_CLC_HOME /usr/share/TEE-CLC-${TEE_VERSION}/

# user setting
RUN \
    mkdir -p ${HOME}/.config/Code/User/ \
    && echo '{"update.mode": "none"}' >${HOME}/.config/Code/User/settings.json \
    && "${STARTUPDIR}"/set_user_permissions.sh "${HOME}"

USER "${HEADLESS_USER_ID}"