# 基于镜像alpine
FROM colorcoding/compiling:ibas-alpine

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 工具版本
ARG TEE_VERSION=14.123.1

# 安装工具
RUN set -x \
# 下载TEE
    && curl -L https://github.com/Microsoft/team-explorer-everywhere/releases/download/${TEE_VERSION}/TEE-CLC-${TEE_VERSION}.zip -O \
# 解压安装
    && unzip -o TEE-CLC-${TEE_VERSION}.zip -d /usr/share/ \
    && ln -s /usr/share/TEE-CLC-${TEE_VERSION}/tf /usr/bin/tf \
# 删除文件
    && rm -rf ./TEE-CLC-${TEE_VERSION}.zip

# 设置环境变量
ENV TF_CLC_HOME /usr/share/TEE-CLC-${TEE_VERSION}/
