# 基于镜像debian
FROM buildpack-deps:stretch-scm

# 维护者
MAINTAINER Niuren.Zhu "niuren.zhu@icloud.com"

# 安装环境
RUN set -x \
    # 安装NODE
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs \
    # 安装TYPESCRIPT
    && npm install -g typescript \
    # 安装JDK
    && apt-get install -y openjdk-8-jdk-headless \
    # 安装MAVEN
    && apt-get install -y maven \
    # 安装转码工具
    && apt-get install -y dos2unix \
    # 安装时区工具
    && apt-get install -y tzdata \
    # 删除源
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 环境变量-JAVA目录
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
# 环境变量-MAVEN目录
ENV MAVEN_HOME /usr/share/maven
# 环境变量-代码目录
ENV CODE_HOME=/home/code

# 初始化环境
RUN mkdir -p ${CODE_HOME}

# 设置工作目录
WORKDIR ${CODE_HOME}