# 基于镜像debian
FROM buildpack-deps:stretch-scm

# 维护者
MAINTAINER Niuren.Zhu "niuren.zhu@icloud.com"

# 安装环境
RUN set -x \
# 更新源
    && apt-get clean && apt-get update \
# 安装JDK
    && apt-get install -y openjdk-8-jdk-headless \
# 安装MAVEN
    && apt-get install -y maven \
# 安装NODE
    && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get install -y nodejs \
# 安装NPM
    && curl -sL https://npmjs.org/install.sh -O \
    && chmod 777 install.sh && ./install.sh
    && rm -rf ./install.sh
# 安装TYPESCRIPT
    && npm install -g typescript \
# 删除源
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*
