# 基于镜像ubuntu
FROM dorowu/ubuntu-desktop-lxde-vnc:latest as builder
# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"
# 安装环境
RUN set -x \
    # 修改源公钥
    && curl -sL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    # 安装NODE
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install -g typescript@3.9.10 uglify-es \
    # 安装基本
    && apt-get install -y gnupg libgconf-2-4 git dos2unix \
    # 安装JDK
    && apt-get install -y openjdk-8-jdk \
    && apt-get install -y maven \
    # 安装其他工具
    && apt-get install -y fcitx-googlepinyin \
    # 删除源
    && apt-get autoremove -y \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*
# 环境变量-JAVA目录
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
# 环境变量-MAVEN目录
ENV MAVEN_HOME /usr/share/maven
COPY conf/maven.settings.xml ${MAVEN_HOME}/conf/settings.xml

# eclipse jee
RUN curl -LfsSo /tmp/eclipse.tar.gz 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2020-06/R/eclipse-jee-2020-06-R-linux-gtk-x86_64.tar.gz' \
    && mkdir -p /usr/share/eclipse \
    && cd /usr/share/eclipse \
    && tar -xf /tmp/eclipse.tar.gz --strip-components=1 \
    && rm -rf /tmp/eclipse.tar.gz \
    && echo "[Desktop Entry]"                    >/usr/share/applications/eclipse.desktop \
    && echo "Name=Eclipse"                       >>/usr/share/applications/eclipse.desktop \
    && echo "Comment=Eclipse"                    >>/usr/share/applications/eclipse.desktop \
    && echo "Exec=/usr/share/eclipse/eclipse"    >>/usr/share/applications/eclipse.desktop \
    && echo "Icon=/usr/share/eclipse/icon.xpm"   >>/usr/share/applications/eclipse.desktop \
    && echo "Terminal=false"                     >>/usr/share/applications/eclipse.desktop \
    && echo "Type=Application"                   >>/usr/share/applications/eclipse.desktop \
    && echo "Categories=Development;IDE;"        >>/usr/share/applications/eclipse.desktop \
    && echo "StartupNotify=false"                >>/usr/share/applications/eclipse.desktop

# vscode
RUN curl -LfsSo /tmp/vscode_amd64.deb 'https://vscode.cdn.azure.cn/stable/a0479759d6e9ea56afa657e454193f72aef85bd0/code_1.48.2-1598353430_amd64.deb' \
    && dpkg -i /tmp/vscode_amd64.deb \
    && rm -rf /tmp/vscode_amd64.deb \
    && echo "[Desktop Entry]"                               >/usr/share/applications/code.desktop \
    && echo "Name=Visual Studio Code"                       >>/usr/share/applications/code.desktop \
    && echo "Comment=Code Editing. Redefined."              >>/usr/share/applications/code.desktop \
    && echo "Exec=/usr/share/code/code --no-sandbox --user-data-dir=/root/.vscode --unity-launch %F"    >>/usr/share/applications/code.desktop \
    && echo "Icon=com.visualstudio.code"                    >>/usr/share/applications/code.desktop \
    && echo "Type=Application"                              >>/usr/share/applications/code.desktop \
    && echo "Terminal=false"                                >>/usr/share/applications/code.desktop \
    && echo "StartupNotify=false"                           >>/usr/share/applications/code.desktop \
    && echo "StartupWMClass=Code"                           >>/usr/share/applications/code.desktop \
    && echo "Categories=Development;IDE;"                   >>/usr/share/applications/code.desktop

