# 基于[windows nano server]镜像
FROM mcr.microsoft.com/windows/servercore:10.0.14393.2551 as installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG OPENJDK_URL=https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10_openj9-0.26.0/OpenJDK8U-jdk_x64_windows_openj9_8u292b10_openj9-0.26.0.zip
ARG OPENJDK_SHA256=3031c1332f40b397a6fce932b34179e0914795c72331e41c330c425d9f10f35a

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -Uri ${Env:OPENJDK_URL} -O openjdk.zip; \
    if ((Get-FileHash openjdk.zip -Algorithm sha256).Hash -ne ${Env:OPENJDK_SHA256}) { \
            Write-Host 'Verifying sha256 FAILED!'; exit 1; \
    }; \
    Expand-Archive -LiteralPath openjdk.zip -DestinationPath 'C:\'; \
    $jdkDirectory=(Get-ChildItem -Directory | ForEach-Object { $_.FullName } | Select-String 'jdk'); \
    Move-Item -Path $jdkDirectory C:\openjdk-8; \
    Remove-Item openjdk.zip -Force;

# 从基础镜像拷贝文件
FROM mcr.microsoft.com/windows/nanoserver:10.0.14393.2551

# Set JAVA_HOME and PATH environment variables
RUN setx /M JAVA_HOME "C:\\openjdk-8" & \
    setx /M PATH "%PATH%;%JAVA_HOME%\\bin"

COPY --from=installer ["/openjdk-8", "/openjdk-8"]

ENV JAVA_HOME=C:\\openjdk-8 \
    ProgramFiles="C:\\Program Files" \
    WindowsPATH="C:\\Windows\\system32;C:\\Windows"
ENV PATH="${WindowsPATH};${JAVA_HOME}\\bin"

ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal"
