# 基于[windows nano server]镜像
FROM colorcoding/openjdk:8-jdk-wincore as installer

# 从基础镜像拷贝文件
FROM mcr.microsoft.com/windows/nanoserver:10.0.14393.2551_zh-cn
# Set JAVA_HOME and PATH environment variables
ENV JAVA_HOME="C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.292.10-openj9" \
    ProgramFiles="C:\\Program Files" \
    WindowsPATH="C:\\Windows\\system32;C:\\Windows"
ENV PATH="${WindowsPATH};${JAVA_HOME}\\bin"

COPY --from=installer ["${JAVA_HOME}", "${JAVA_HOME}"]

ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=C:\Windows\Temp\.scc\,readonly,nonFatal"