# 基于[windows server core 2016]镜像
FROM mcr.microsoft.com/windows/servercore:10.0.14393.7259

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG OPENJDK_URL=https://github.com/ibmruntimes/semeru8-binaries/releases/download/jdk8u442-b06_openj9-0.49.0/ibm-semeru-open-jdk_x64_windows_8u442b06_openj9-0.49.0.msi
ARG OPENJDK_SHA256=576260cc254dd281417ef10bb466b4327f51053e0b69f4c47f6ddfa55651b347

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -Uri ${Env:OPENJDK_URL} -O 'openjdk.msi' ; \
    IF ((Get-FileHash openjdk.msi -Algorithm sha256).Hash -ne ${Env:OPENJDK_SHA256}) { \
    Write-Host 'Verifying sha256 FAILED!'; exit 1; \
    }; \
    New-Item -ItemType Directory -Path C:\temp | Out-Null; \
    Write-Host 'Installing using MSI ...'; \
    $proc = Start-Process -FilePath "msiexec.exe" -ArgumentList '/i', 'openjdk.msi', '/L*V', 'C:\temp\OpenJDK.log', \
    '/quiet', 'ADDLOCAL=FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome' -Wait -Passthru; \
    $proc.WaitForExit() ; \
    IF ($proc.ExitCode -ne 0) { \
    Write-Host 'FAILED installing MSI!' ; exit 1; \
    }; \
    Remove-Item -Path C:\temp -Force -Recurse | Out-Null; \
    Remove-Item openjdk.msi -Force;

ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=C:\Windows\Temp\.scc\,nonFatal"