# 基于镜像alpine
FROM ginuerzh/gost

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 安装环境
RUN set -x \
    # 更新源
    && apk update \
    # 安装CURL
    && apk add --no-cache curl \
    # 安装UNZIP
    && apk add --no-cache unrar \
    # 安装GIT
    && apk add --no-cache git \
    # 安装FileBrowser环境
    && apk add --no-cache ca-certificates \
    && apk add --no-cache mailcap \
    # 删除源
    && rm -rf /var/cache/apk/*

# 安装FileBrowser
ENV FB_VERSION v2.13.0
RUN set -x \
    # 下载文件
    && curl -sL https://github.com/filebrowser/filebrowser/releases/download/${FB_VERSION}/linux-amd64-filebrowser.tar.gz -O \
    # 解压安装
    && mkdir -p /usr/share/filebrowser \
    && tar zxvf linux-amd64-filebrowser.tar.gz -C /usr/share/filebrowser \
    && ln -s /usr/share/filebrowser/filebrowser /usr/bin/filebrowser \
    # 删除文件
    && rm -rf linux-amd64-filebrowser.tar.gz

# 暴露端口
EXPOSE 80 8080 8090

# 初始化脚本
COPY ./supporting/gofile/entrypoint.sh /entrypoint.sh
RUN ["chmod", "+x", "/entrypoint.sh"]

# 执行命令
ENTRYPOINT ["/entrypoint.sh"]

# docker build --force-rm --no-cache -f ./dockerfile -t gofile ./