# 基于镜像alpine
FROM alpine:latest

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 安装环境
RUN set -x \
# 更新源
    && apk update \
# 安装mysql-client
    && apk add --no-cache mysql-client \
# 删除源
    && rm -rf /var/cache/apk/*

# 初始化环境
RUN mkdir -p /sqls

# 工作目录
WORKDIR /sqls
