# 基于Centos7 + JAVA8 + OpenJ9

FROM ibm-semeru-runtimes:open-8-jre-centos7

LABEL name="Nexus Repository Manager" \
    maintainer="Niuren.Zhu <niuren.zhu@icloud.com>" \
    vendor=ColorCoding \
    version="3.69.0-02" \
    release="3.69.0" \
    url="https://sonatype.com" \
    summary="The Nexus Repository Manager server \
    with universal support for popular component formats." \
    description="The Nexus Repository Manager server \
    with universal support for popular component formats." \
    run="docker run -d --name NAME \
    -p 8081:8081 \
    IMAGE" \
    stop="docker stop NAME" \
    com.sonatype.license="Apache License, Version 2.0" \
    com.sonatype.name="Nexus Repository Manager base image" \
    io.k8s.description="The Nexus Repository Manager server \
    with universal support for popular component formats." \
    io.k8s.display-name="Nexus Repository Manager" \
    io.openshift.expose-services="8081:8081" \
    io.openshift.tags="Sonatype,Nexus,Repository Manager"

ARG NEXUS_VERSION=3.69.0-02
ARG NEXUS_JAVA_VERSION=java8
ARG NEXUS_DOWNLOAD_URL=https://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz
ARG NEXUS_DOWNLOAD_SHA256_HASH=4161a1bb43d92ad8ca6185fa0da2c0f02dfd62280c5b6e4ac4419df4aecaf55f

# Configure nexus runtime
ENV SONATYPE_DIR=/opt/sonatype
ENV NEXUS_HOME=${SONATYPE_DIR}/nexus \
    NEXUS_DATA=/nexus-data \
    NEXUS_CONTEXT='' \
    SONATYPE_WORK=${SONATYPE_DIR}/sonatype-work \
    DOCKER_TYPE='rh-docker'

# Setup user
RUN groupadd --gid 200 -r -f nexus \
    && useradd --uid 200 -r nexus -g nexus -s /bin/false -d /opt/sonatype/nexus -c 'Nexus Repository Manager user'

WORKDIR ${SONATYPE_DIR}

# Download nexus & setup directories
RUN curl -L ${NEXUS_DOWNLOAD_URL} --output nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz \
    && echo "${NEXUS_DOWNLOAD_SHA256_HASH} nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz" > nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz.sha256 \
    && sha256sum -c nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz.sha256 \
    && tar -xvf nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz \
    && rm -f nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz nexus-${NEXUS_VERSION}-${NEXUS_JAVA_VERSION}-unix.tar.gz.sha256 \
    && mv nexus-${NEXUS_VERSION} $NEXUS_HOME \
    && chown -R nexus:nexus ${SONATYPE_WORK} \
    && mv ${SONATYPE_WORK}/nexus3 ${NEXUS_DATA} \
    && ln -s ${NEXUS_DATA} ${SONATYPE_WORK}/nexus3

# Removing java memory settings from nexus.vmoptions since now we use INSTALL4J_ADD_VM_PARAMS
RUN sed -i '/^-Xms/d;/^-Xmx/d;/^-XX:MaxDirectMemorySize/d' $NEXUS_HOME/bin/nexus.vmoptions

# Legacy start script
RUN echo "#!/bin/bash" >> ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
    && echo "cd /opt/sonatype/nexus" >> ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
    && echo "exec ./bin/nexus run" >> ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
    && chmod a+x ${SONATYPE_DIR}/start-nexus-repository-manager.sh \
    && sed -e '/^nexus-context/ s:$:${NEXUS_CONTEXT}:' -i ${NEXUS_HOME}/etc/nexus-default.properties

VOLUME ${NEXUS_DATA}

EXPOSE 8081
USER nexus

ENV INSTALL4J_ADD_VM_PARAMS="-Xms2048m -Xmx2048m -XX:MaxDirectMemorySize=2048m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"

CMD ["/opt/sonatype/nexus/bin/nexus", "run"]