# 基于[windows nano server]镜像
FROM colorcoding/tomcat:9.0-wincore as installer

# 拷贝tomcat文件
FROM colorcoding/openjdk:8-jdk-winnano

ENV CATALINA_HOME=C:\\apache-tomcat
ENV PATH=${CATALINA_HOME}\\bin;${PATH};

COPY --from=installer ["${CATALINA_HOME}", "${CATALINA_HOME}"]

# 根目录创建启动命令
RUN echo call catalina.bat run>C:\\EntryPoint.bat

WORKDIR ${CATALINA_HOME}

EXPOSE 8080
ENTRYPOINT ["C:\\EntryPoint.bat"]