# 基于[windows server core 2016]镜像
FROM colorcoding/openjdk:8-jdk-wincore

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 使用Powershell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 安装TOMCAT
ENV TOMCAT_MAJOR 9
ENV TOMCAT_VERSION 9.0.120
ARG TOMCAT_SHA512=fecea5786820f6fee1c0a3f9a47dc9d9d8208b7cb27af85407c8c97e7b5d2884212f36d5be679be01caade2091fa6d0815e4e03b6115b740fd5d8509f254856c

ENV CATALINA_HOME C:\\apache-tomcat

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -Uri "https://www.apache.org/dyn/closer.cgi?action=download`&filename=tomcat/tomcat-${Env:TOMCAT_MAJOR}/v${Env:TOMCAT_VERSION}/bin/apache-tomcat-${Env:TOMCAT_VERSION}-windows-x64.zip" -OutFile 'C:\apache-tomcat.zip'; \
    IF ((Get-FileHash 'C:\apache-tomcat.zip' -Algorithm sha512).Hash -ne ${Env:TOMCAT_SHA512}) { \
        Write-Host 'Verifying sha512 FAILED!'; exit 1; \
    }; \
    Expand-Archive -LiteralPath 'C:\apache-tomcat.zip' -DestinationPath 'C:\'; \
    Move-Item -Path ${Env:CATALINA_HOME}-${Env:TOMCAT_VERSION} ${Env:CATALINA_HOME}; \
    Remove-Item -Force -LiteralPath 'C:\apache-tomcat.zip'; \
    SETX /m PATH $(${Env:PATH} + \";${Env:CATALINA_HOME}\bin\");

SHELL ["cmd", "/S", "/C"]

WORKDIR ${CATALINA_HOME}

EXPOSE 8080
CMD ["catalina.bat", "run"]
